<?php

namespace App\Console\Commands;

use App\Services\AIDetectionService;
use Illuminate\Console\Command;

class TestRepoFlow extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:test-repo-flow';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info("🚀 Starting AI Analysis Test with Gemini...");

        $aiService = app(AIDetectionService::class);

        // AI Pattern Test
        $testCode = '<?php

        namespace App\Services;

        /**
         * High-performance data processor.
         * Generated by the system to handle heavy loads.
         */
        class DataProcessor {
            public function process(array $data) {
                // Uniform and clean logic
                return array_map(function($item) {
                    return [
                        "id" => $item["id"],
                        "status" => "processed",
                        "timestamp" => now()
                    ];
                }, $data);
            }

            public function validate($input) {
                if (empty($input)) {
                    throw new \Exception("Input cannot be empty");
                }
                return true;
            }
        }';

        $this->warn("\nTesting AI-style Snippet...");
        $result = $aiService->analyzeFile('UserRepo.php', $testCode);

        $this->table(
            ['Metric', 'Value'],
            [
                ['Classification', $result['classification']],
                ['Confidence', $result['confidence_score'] . '%'],
                ['Source', $result['source']],
                ['Explanation', $result['explanation']]
            ]
        );

        if (!empty($result['signals'])) {
            $this->info("Signals Detected:");
            foreach ($result['signals'] as $key => $val) {
                $this->line("- " . str_replace('_', ' ', $key) . ": " . ($val ? '✅' : '❌'));
            }
        }
    }
}
